# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170901_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='country',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='Images/None/NoUser.jpg', upload_to='Images/Users'),
        ),
    ]
