# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20170906_0641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(blank='True', max_length=255, unique=True),
        ),
    ]
