# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 10:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('N', 'Choose field'), ('E', 'Email'), ('P', 'Phone'), ('U', 'User'), ('A', 'Address')], default='N', max_length=255)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 10, 11, 10, 23, 20, 791891))),
                ('products', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='Checks')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Created'), ('PAY', 'Payed'), ('RUN', 'Confirmed'), ('DEL', 'Canceled'), ('OK', 'Delivered')], default='NEW', max_length=255),
        ),
        migrations.AddField(
            model_name='check',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='root.Order'),
        ),
    ]
