# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 17:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_auto_20171011_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 13, 17, 32, 17, 652475, tzinfo=utc)),
        ),
    ]
