# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 11:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_auto_20171013_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='field',
            field=models.CharField(choices=[('N', 'Choose field'), ('E', 'Email'), ('P', 'Phone'), ('U', 'Username'), ('A', 'Address')], default='N', max_length=255),
        ),
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 17, 11, 39, 23, 891046, tzinfo=utc)),
        ),
    ]
