# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 11:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_auto_20171017_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 17, 11, 45, 52, 364811)),
        ),
    ]
