# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 11:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_auto_20171017_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 17, 11, 50, 39, 832507, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 17, 11, 50, 39, 830405, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 17, 11, 50, 39, 829266, tzinfo=utc)),
        ),
    ]
