# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-17 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_auto_20171017_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='root.Product'),
        ),
    ]
