# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_auto_20171017_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterion',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterion', to='root.Category'),
        ),
    ]
