# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0014_auto_20171026_0049'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProducts',
            new_name='OrderProduct',
        ),
    ]
