# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0015_auto_20171026_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
