# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0016_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
