# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 11:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0019_auto_20171028_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 28, 14, 40, 49, 143851)),
        ),
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 28, 14, 40, 49, 142586)),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 28, 14, 40, 49, 141406)),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 28, 14, 40, 49, 141622)),
        ),
    ]
