# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0022_remove_order_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='surname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
