# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-28 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0023_order_surname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_datetime',
        ),
        migrations.RemoveField(
            model_name='order',
            name='surname',
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
