# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0024_auto_20171028_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='file',
        ),
    ]
