# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0025_remove_check_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_check', to='root.Order'),
        ),
    ]
