# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-29 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0026_auto_20171029_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='code',
            field=models.CharField(default='', max_length=8),
        ),
    ]
